# Generated by Django 4.2.7 on 2023-11-17 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='connections',
            new_name='following',
        ),
    ]
