# Generated by Django 4.2.7 on 2023-11-09 23:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
